# docker-compose.yml
version: '3.8'
services:
  postgres-aps:
    image: postgres:latest
    container_name: postgres-aps
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
